[package]
name = "pilatus-examples-leptos"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
gloo-net.workspace = true
gloo-timers = { workspace = true, features = ["futures", "futures-core"] }
leptos.workspace = true
leptos_router.workspace = true
leptos_forge_utils_leptos.workspace = true
pilatus = { workspace = true, default-features = false }
pilatus-tick = { workspace = true, features = ["unstable"] }
pilatus-leptos.workspace = true
serde.workspace = true
serde_json.workspace = true
reactive_stores.workspace = true
thaw.workspace = true
thaw_utils.workspace = true
tokio = { version = "1", features = ["time"], optional = true }
