[package]
name = "pilatus-emulation-camera-leptos"
version.workspace = true
edition.workspace = true

[dependencies]
futures-util.workspace = true
gloo-net.workspace = true
js-sys.workspace = true
leptos.workspace = true
pilatus.workspace = true
pilatus-leptos.workspace = true
pilatus-emulation-camera = { workspace = true, features = ["impex", "unstable"] }
pilatus-engineering-leptos = { path = "../pilatus-engineering-leptos" }
thaw.workspace = true
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { workspace = true, features = ["File", "FileList", "HtmlElement", "DragEvent", "DataTransfer"] }
