[workspace]
resolver = "3"
members = [
    "pilatus-aravis-leptos",
    "app-backend",
    "pilatus-leptos",
    "pilatus-leptos-app",
    "pilatus-engineering-leptos",
    "pilatus-examples-leptos",
    "pilatus-emulation-camera-leptos"
]

default-members = [
    "pilatus-aravis-leptos",
    "pilatus-leptos",
    "pilatus-leptos-app",
    "pilatus-engineering-leptos",
    "pilatus-examples-leptos",
    "pilatus-emulation-camera-leptos"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
axum = "0.8"
chrono = "0.4"
egui = "0.33"
eframe = "0.33"
futures-channel = "0.3"
futures-util = "0.3"
gloo-events = "0.3"
gloo-net = "0.7"
gloo-timers = "0.4"
gloo-utils = "0.3"
image = { version = "0.25", default-features = false }
imbuf = "0.3"
imanot = { git = "https://github.com/mineichen/imanot.git" }
imask = { git = "https://github.com/mineichen/imask.git" }
impex = { git = "https://github.com/mineichen/impex", features = ["visitor"] }
js-sys = "0.3"
leptos = "0.8"
leptos_axum = "0.8"
leptos_router = "0.8"
leptos_meta = "0.8"
leptos_forge_utils_leptos = "0.6"
minfac = "0.1"
pilatus = { git = "https://github.com/mineichen/pilatus.git", default-features = false }
pilatus-aravis = { git = "https://github.com/mineichen/pilatus-aravis.git" }
pilatus-aravis-rt = { git = "https://github.com/mineichen/pilatus-aravis.git" }
pilatus-axum = { git = "https://github.com/mineichen/pilatus.git" }
pilatus-leptos = { path = "pilatus-leptos" }
pilatus-examples-leptos = { path = "pilatus-examples-leptos"}
pilatus-emulation-camera = { git = "https://github.com/mineichen/pilatus.git" }
pilatus-emulation-camera-rt = { git = "https://github.com/mineichen/pilatus.git" }
pilatus-engineering = { git = "https://github.com/mineichen/pilatus.git" }
pilatus-engineering-rt = { git = "https://github.com/mineichen/pilatus.git" }
pilatus-tick = { git = "https://github.com/mineichen/pilatus.git" }
reactive_graph = "0.2"
reactive_stores = "0.3"
serde = "1"
serde_json = "1"
thaw = { git = "https://github.com/thaw-ui/thaw.git" }
thaw_utils = { git = "https://github.com/thaw-ui/thaw.git" }
thiserror = "2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-streams = "0.5"
web-sys = "0.3"


# Optimize pilatus-engineering-leptos even in debug mode for better performance
[profile.dev.package.pilatus-engineering-leptos]
opt-level = 2

[profile.dev.package.imanot]
opt-level = 2

# [patch."https://github.com/mineichen/pilatus.git"]
# pilatus = { path = "../pilatus/pilatus" }
# pilatus-rt = { path = "../pilatus/pilatus-rt" }
# pilatus-axum = { path = "../pilatus/pilatus-axum" }
# pilatus-axum-rt = { path = "../pilatus/pilatus-axum-rt" }
# pilatus-engineering = { path = "../pilatus/pilatus-engineering" }
# pilatus-engineering-rt = { path = "../pilatus/pilatus-engineering-rt" }
# pilatus-emulation-camera = { path = "../pilatus/pilatus-emulation-camera" }
# pilatus-emulation-camera-rt = { path = "../pilatus/pilatus-emulation-camera-rt" }
# pilatus-tick = { path = "../pilatus/examples/tick" }

# [patch."https://github.com/mineichen/pilatus-aravis.git"]
# pilatus-aravis.path = "../pilatus-aravis/pilatus-aravis"
# pilatus-aravis-rt.path = "../pilatus-aravis/pilatus-aravis-rt"

# [patch."https://github.com/mineichen/imask.git"]
# imask.path = "../imask"

# [patch."https://github.com/mineichen/imanot.git"]
# imanot.path = "../imanot/imanot"

# [patch.crates-io]
# imbuf.path = "../imbuf"
