[package]
name = "pilatus-leptos"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
gloo-net.workspace = true
gloo-timers = { workspace = true, features = ["futures", "futures-core"] }
impex.workspace = true
leptos.workspace = true
leptos_router.workspace = true
leptos_forge_utils_leptos.workspace = true
pilatus.workspace = true
reactive_stores.workspace = true
reactive_graph.workspace = true
serde.workspace = true
serde_json.workspace = true
thaw.workspace = true
thaw_utils.workspace = true
thiserror.workspace = true
uuid = "1"
web-sys = { workspace = true, features = ["Window", "Location"] }
futures-util.workspace = true

[dev-dependencies]
leptos_reactive = "0.6.15"
