[package]
name = "pilatus-leptos"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
gloo-net.workspace = true
gloo-timers = { version = "0.3", features = ["futures", "futures-core"] }
impex.workspace = true
leptos.workspace = true
leptos_router.workspace = true
leptos_forge_utils_leptos.workspace = true
pilatus.workspace = true
reactive_stores.workspace = true
# reactive_graph.workspace = true
serde.workspace = true
serde_json.workspace = true
thaw.workspace = true
thaw_utils.workspace = true
tokio = { version = "1", features = ["time"], optional = true }

[dev-dependencies]
pilatus-leptos = { path = ".", features = ["ssr"] }

[features]
hydrate = ["leptos/hydrate", "thaw/hydrate"]
ssr = [
    "tokio",
    "leptos/ssr",
    "thaw/ssr",
]
