[package]
name = "app"
version.workspace = true
edition.workspace = true

#[lib]
#crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
leptos = { workspace = true, features = ["csr"] }
leptos_router.workspace = true
console_error_panic_hook = "0.1"
leptos_meta.workspace = true
pilatus.workspace = true
thaw.workspace = true
thaw_utils.workspace = true
pilatus-leptos.workspace = true
pilatus-examples-leptos = { path = "../pilatus-examples-leptos", optional = true }
pilatus-engineering-leptos = { path = "../pilatus-engineering-leptos" }
pilatus-emulation-camera-leptos = { path = "../pilatus-emulation-camera-leptos" }

[features]
examples = ["pilatus-examples-leptos"]


