[watch]
watch = [
    "../pilatus-leptos",
    ".",
    "../pilatus-engineering-leptos",
    "../pilatus-examples-leptos",
    "../pilatus-emulation-camera-leptos"
]

[[proxy]]
backend = "http://localhost:4123/api"

[[proxy]]
backend = "ws://localhost:4123/api/recipe/stream"
ws = true

[[proxy]]
backend = "ws://localhost:4123/api/image/subscribe"
