[package]
name = "pilatus-engineering-leptos"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
eframe.workspace = true
egui.workspace = true
egui-pixels.workspace = true
futures.workspace = true
gloo-net.workspace = true
gloo.workspace = true
image-buffer = { git = "https://github.com/mineichen/image-buffer.git", branch = "main" }
js-sys.workspace = true
leptos.workspace = true
pilatus-leptos.workspace = true
web-sys.workspace = true
