[package]
name = "pilatus-engineering-leptos"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
eframe.workspace = true
egui.workspace = true
egui-pixels.workspace = true
futures.workspace = true
gloo-events.workspace = true
gloo-net.workspace = true
gloo-timers.workspace = true
imbuf.workspace = true
js-sys.workspace = true
leptos.workspace = true
pin-project-lite = "0.2"
thiserror.workspace = true
wasm-bindgen = "0.2"
web-sys = { workspace = true, features = ["File", "FileList", "HtmlElement", "DragEvent", "DataTransfer", "Document", "VisibilityState"] }
