[package]
name = "pilatus-leptos-app"
version.workspace = true
edition.workspace = true


[dependencies]
anyhow.workspace = true
leptos = { workspace = true, features = ["csr"] }
leptos_router.workspace = true
console_error_panic_hook = "0.1"
leptos_meta.workspace = true
pilatus.workspace = true
thaw.workspace = true
thaw_utils.workspace = true
pilatus-leptos.workspace = true
pilatus-examples-leptos = { path = "../pilatus-examples-leptos", optional = true }
pilatus-emulation-camera-leptos = { path = "../pilatus-emulation-camera-leptos", optional = true }
pilatus-aravis-leptos = { path = "../pilatus-aravis-leptos", optional = true }

[features]
default = ["aravis", "emulation-camera"]
aravis = ["pilatus-aravis-leptos"]
emulation-camera = ["pilatus-emulation-camera-leptos"]
examples = ["pilatus-examples-leptos"]


